
-----------------
CREATE TABLE INGREDIENTS(
    INGRED_NAME VARCHAR2(20 CHAR) PRIMARY KEY,
    INGRED_CATEGORY VARCHAR2(5 CHAR) NOT NULL CHECK (INGRED_CATEGORY IN('추가토핑','채소','빵','소스','메뉴')),
    INGRED_CALORIE NUMBER(5),
    INGRED_PRICE_15 NUMBER(5),
    INGRED_PRICE_30 NUMBER(5),
    INGRED_RECOMMEND_SAUCE VARCHAR2(20 CHAR)
);

CREATE TABLE USERS(
    USER_ID VARCHAR2(20 CHAR) PRIMARY KEY,
    USER_PASS VARCHAR2(20 CHAR) NOT NULL,
    USER_NAME VARCHAR2(10 CHAR) NOT NULL,
    USER_PHONE VARCHAR2(20 CHAR) NOT NULL,
    USER_EMAIL VARCHAR2(100 CHAR) 
);

CREATE TABLE ORDERS(
    ORDER_ID NUMBER(4) PRIMARY KEY,    
    ORDER_BREAD_LEN NUMBER(2) NOT NULL CHECK(ORDER_BREAD_LEN IN(15 , 30)),
    ORDER_MENU VARCHAR2(20 CHAR) NOT NULL  REFERENCES INGREDIENTS(INGRED_NAME),
    ORDER_EXTRA VARCHAR2(20 CHAR) NOT NULL  REFERENCES INGREDIENTS(INGRED_NAME),
    ORDER_BREAD VARCHAR2(20 CHAR) NOT NULL REFERENCES INGREDIENTS(INGRED_NAME),
    ORDER_SAUCE VARCHAR2(20 CHAR) NOT NULL REFERENCES INGREDIENTS(INGRED_NAME),
    ORDER_PRICE NUMBER(10) NOT NULL,
    ORDER_CALORIE NUMBER(10) NOT NULL,
    ORDER_USER VARCHAR2(20 CHAR) NOT NULL REFERENCES USERS(USER_ID),
    ORDER_TEXT VARCHAR2(100 CHAR),
    ORDER_IS_MY_MENU VARCHAR2(5 CHAR) DEFAULT 'FALSE' CHECK (ORDER_IS_MY_MENU IN('TRUE','FALSE') ),
    ORDER_QUANTITY NUMBER(2),
    ORDER_BASKET NUMBER(4) NOT NULL REFERENCES BASKETS(BASKET_ID)
);

CREATE TABLE ORDER_VEGETABLES(
    ORDER_VEG_ID NUMBER(4) PRIMARY KEY,
    ORDER_VEG_NAME VARCHAR2(20 CHAR) NOT NULL REFERENCES INGREDIENTS(INGRED_NAME),
    ORDER_VEG_AMOUNT NUMBER(1) DEFAULT 1 CHECK(ORDER_VEG_AMOUNT IN(0,1,2)),  --0은 없음, 1은 보통 , 2는 많이
    ORDER_ID NUMBER(4) NOT NULL REFERENCES ORDERS(ORDER_ID)
);

DROP TABLE ORDER_VEGETABLES CASCADE CONSTRAINTS

CREATE TABLE BASKETS(
    BASKET_ID NUMBER(4) PRIMARY KEY,
    BASKET_USER_ID VARCHAR2(20 CHAR) NOT NULL REFERENCES USERS(USER_ID),
    BASKET_PRICE NUMBER(10) NOT NULL,
    BASKET_DATE DATE NOT NULL
);




-----시퀀스
CREATE SEQUENCE ORDER_SEQ 
START WITH 1
INCREMENT BY 1
NOCACHE; 

CREATE SEQUENCE ORDER_VEG_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE; 


CREATE SEQUENCE BASKET_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;


-----test data insert

--빵
INSERT INTO INGREDIENTS(INGRED_NAME, INGRED_CATEGORY, INGRED_CALORIE) 
VALUES('허니오트', '빵', 230);
INSERT INTO INGREDIENTS(INGRED_NAME, INGRED_CATEGORY, INGRED_CALORIE) 
VALUES('하티', '빵', 210);
INSERT INTO INGREDIENTS(INGRED_NAME, INGRED_CATEGORY, INGRED_CALORIE) 
VALUES('위트', '빵', 210);

--채소
INSERT INTO INGREDIENTS(INGRED_NAME, INGRED_CATEGORY, INGRED_CALORIE) 
VALUES('양상추', '채소', 5);
INSERT INTO INGREDIENTS(INGRED_NAME, INGRED_CATEGORY, INGRED_CALORIE) 
VALUES('토마토', '채소', 5);
INSERT INTO INGREDIENTS(INGRED_NAME, INGRED_CATEGORY, INGRED_CALORIE) 
VALUES('오이', '채소', 5);

--소스
INSERT INTO INGREDIENTS(INGRED_NAME, INGRED_CATEGORY, INGRED_CALORIE) 
VALUES('리치시저', '소스', 100);
INSERT INTO INGREDIENTS(INGRED_NAME, INGRED_CATEGORY, INGRED_CALORIE) 
VALUES('랜치드레싱', '소스', 110);
INSERT INTO INGREDIENTS(INGRED_NAME, INGRED_CATEGORY, INGRED_CALORIE) 
VALUES('마요네즈', '소스', 110);

--추가토핑
INSERT INTO INGREDIENTS(INGRED_NAME, INGRED_CATEGORY, INGRED_PRICE_15, INGRED_PRICE_30) 
VALUES('더블업', '추가토핑', 1500, 3000);
INSERT INTO INGREDIENTS(INGRED_NAME, INGRED_CATEGORY, INGRED_PRICE_15, INGRED_PRICE_30) 
VALUES('에그마요', '추가토핑', 1500, 3000);
INSERT INTO INGREDIENTS(INGRED_NAME, INGRED_CATEGORY, INGRED_PRICE_15, INGRED_PRICE_30) 
VALUES('오믈렛', '추가토핑', 1100, 2200);

--메뉴
INSERT INTO INGREDIENTS(INGRED_NAME, INGRED_CATEGORY, INGRED_CALORIE,INGRED_PRICE_15, INGRED_PRICE_30, INGRED_RECOMMEND_SAUCE) 
VALUES('로티세리 치킨', '메뉴', 350, 5900, 9500,'리치시저');
INSERT INTO INGREDIENTS(INGRED_NAME, INGRED_CATEGORY, INGRED_CALORIE,INGRED_PRICE_15, INGRED_PRICE_30, INGRED_RECOMMEND_SAUCE) 
VALUES('풀드포크', '메뉴', 420, 5900, 9900,'스모키바비큐');
INSERT INTO INGREDIENTS(INGRED_NAME, INGRED_CATEGORY, INGRED_CALORIE,INGRED_PRICE_15, INGRED_PRICE_30, INGRED_RECOMMEND_SAUCE) 
VALUES('에그마요', '메뉴', 480, 4300, 8000,'허니머스타드');

SELECT * FROM INGREDIENTS; 

--사용자
INSERT INTO USERS VALUES('C62','123123', '남시욱', '010-123-1234', 'C62@naver.com');
INSERT INTO USERS VALUES('coding_genius','9999', '최동철', '010-999-9999', 'cg91@naver.com');
INSERT INTO USERS VALUES('captian_kim','0000', '김승현', '010-000-0000', 'ck@gmail.com');

SELECT * FROM orders;


--회원가입
SELECT USER_ID FROM USERS WHERE USER_ID = ?; --(중복여부)
INSERT INTO USERS(USER_ID,USER_PASS,USER_NAME,USER_PHONE,USER_EMAIL) VALUES (?,?,?,?,?);--(회원정보 입력)

--로그인
SELECT COUNT FROM USERS
WHERE USER_ID:= ? AND USER_PASS:=?;

--마이메뉴(최근 주문내역 3개)
SELECT TOP 3 BASKET_ID FROM BASKETS WHERE BASKET_USER_ID ORDER BY BASKET_DATE;

SELECT BASKET_ID FROM BASKETS WHERE ROWNUM <=3 ORDER BY BASKET_USER_ID; 

--총칼로리
INSERT INTO BASKET_PRICE =(SELECT SUM(ORDER_PRICE) FROM ORDERS WHERE ORDER_USER=USER_ID) AS 총 금액 FROM BASKETS;
UPDATE BASKETS SET BASKET_PRICE = SUM(ORDER_PRICE) WHERE ORDER_USER=USER_ID;
--ORDER
--메뉴고르기
